# Generated by Django 5.0.1 on 2024-03-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sizechart_fielddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizechart',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
