# Generated by Django 5.0.1 on 2024-03-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sizechart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizechart',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
