# Generated by Django 5.0.1 on 2024-03-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sizechart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizechart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sizechart',
            name='length',
        ),
        migrations.RemoveField(
            model_name='sizechart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sizechart',
            name='waist',
        ),
        migrations.CreateModel(
            name='SizeChartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sizechart/')),
                ('chart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.sizechart')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Large')], max_length=3)),
                ('waist', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('chart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.sizechart')),
            ],
        ),
    ]
