# Generated by Django 5.0.1 on 2024-04-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBannerThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(upload_to='ads/banner')),
            ],
            options={
                'verbose_name': 'Banner Add Images THree 438Width 240px Height',
                'verbose_name_plural': 'Banner Add Images THree 438Width 240px Height',
            },
        ),
    ]
