# Generated by Django 5.0.1 on 2024-04-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_adbannerthree_ad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBannersTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=20)),
                ('title_2', models.CharField(max_length=20)),
                ('title_3', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='home/ads/')),
            ],
            options={
                'verbose_name': 'HomePageBannersTwo 1375px Widht 520px Height',
                'verbose_name_plural': 'HomePageBannersTwo 1375px Widht 520px Height',
            },
        ),
    ]
