# Generated by Django 5.0.1 on 2024-04-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_createyourownpagesbanners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=20)),
                ('title_2', models.CharField(max_length=20)),
                ('title_3', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='home/ads/')),
            ],
            options={
                'verbose_name': 'Category 1375px Widht 409px Height',
                'verbose_name_plural': 'Category 1375px Widht 409px Height',
            },
        ),
        migrations.AlterModelOptions(
            name='createyourownpagesbanners',
            options={'verbose_name': 'CreateYourOwn 1375px Widht 409px Height', 'verbose_name_plural': 'CreateYourOwn 1375px Widht 409px Height'},
        ),
    ]
