# Generated by Django 5.0.1 on 2024-04-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_categorypagebanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbannerthree',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
