# Generated by Django 5.0.1 on 2024-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
