# Generated by Django 5.0.1 on 2024-04-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbannerthree',
            options={'verbose_name': 'Banner Add Images THree 438Width 240px Height', 'verbose_name_plural': 'Banner Add Images THree 438Width 240px Height'},
        ),
        migrations.RenameField(
            model_name='adbannerthree',
            old_name='image',
            new_name='ad_image',
        ),
    ]
