# Generated by Django 5.0.1 on 2024-04-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_adbannerthree_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdBannerThree',
        ),
    ]
