# Generated by Django 5.0.1 on 2024-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_text', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to='photos/logos/')),
                ('images', models.ImageField(upload_to='photos/custom_products')),
                ('images_hover', models.ImageField(upload_to='photos/custom_products_hover')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
