# Generated by Django 5.0.1 on 2024-02-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customkit', '0005_cart_cartitem_custom_variations_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart_Custom',
        ),
    ]
