# Generated by Django 5.0.1 on 2024-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customkit', '0006_rename_cart_cart_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/custom_logos')),
            ],
        ),
    ]
