# Generated by Django 5.0.1 on 2024-03-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customkit', '0008_customorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomOrder',
        ),
    ]
