# Generated by Django 5.0.1 on 2024-03-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customkit', '0010_customorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
