# Generated by Django 5.0.1 on 2024-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customkit', '0012_alter_customorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='sizes',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=10),
        ),
    ]
